export const TOOLTIP_HINTS: Record<string, string> = {
    initial_capital: "Starting account balance in USD",
    risk_per_trade: "Percentage of capital risked per single trade (e.g. 1.0 = 1%)",
    max_drawdown: "Maximum allowed decline in account equity before stopping",
    leverage: "Multiplier for position size (technical use only, risk is controlled by % per trade)",

    symbol: "Trading pair to backtest (e.g. BTC/USDT)",
    start_date: "Backtest start date",
    end_date: "Backtest end date",
    timeframe_primary: "Higher timeframe for trend direction / EMA filter (e.g. 4h, 1d)",
    timeframe_secondary: "Lower timeframe for pattern detection and trade entries (e.g. 15m, 1h)",
    trailing_stop_distance: "Distance to trail the stop loss behind price (e.g. 0.02 = 2%)",
    breakeven_trigger_r: "Profit multiplier to trigger move to breakeven (e.g. 1.0 = Move stop to entry when profit hits 1R)",
    use_breakeven_sl: "Enable moving stop loss to breakeven after price reaches the configured R multiple.",
    breakeven_sl: "R multiple required before the stop moves to breakeven (for example 1.0 means move SL to entry at +1R).",
    dynamic_position_sizing: "Adjust position size based on current capital/risk",
    position_cap_adverse: "Worst-case gap assumption for position cap (0.5=50%). Min 0.5 ensures max_drawdown is never exceeded. Higher = more conservative.",

    primary_timeframe: "The main timeframe for candle analysis (e.g. 4h, 1h)",
    min_range_factor: "Minimum candle range (high-low) relative to ATR. Candle range must be ≥ ATR × this factor. Filters flat markets.",
    use_pinbar_quality_filter: "Add stricter geometry checks for pin bars after TA-Lib detects a candidate.",
    pinbar_min_wick_to_body_ratio: "Minimum dominant wick/body ratio for a pin bar quality pass.",
    pinbar_max_opposite_wick_to_range: "Maximum allowed opposite wick as a share of total candle range for pin bars.",
    pinbar_close_near_extreme_threshold: "How close the close must be to the rejection extreme. 0.65 means the close must finish in the top/bottom 35% of the bar.",
    use_engulfing_quality_filter: "Add stricter body and close-location checks for engulfing candles after TA-Lib detects a candidate.",
    engulfing_min_body_to_range: "Minimum body size as a share of the current candle range for engulfing quality.",
    engulfing_min_body_to_atr: "Minimum body size in ATR multiples for engulfing quality.",
    engulfing_min_body_engulf_ratio: "Current engulfing body must be at least this multiple of the previous candle body.",
    engulfing_max_opposite_wick_to_range: "Maximum allowed wick against the direction of the engulfing candle.",
    engulfing_require_close_through_prev_extreme: "Require the engulfing candle to close beyond the previous candle high/low for extra confirmation.",
    use_trend_filter: "Enable/Disable trading only in direction of EMA trend",
    trend_ema_period: "Period for Exponential Moving Average to determine trend direction",
    risk_reward_ratio: "Target Profit/Risk ratio for trade exits",
    sl_buffer_atr: "Buffer added to Stop Loss based on ATR (volatility)",
    poi_zone_upper_atr_mult: "ATR multiplier for the upper side of the HTF POI zone.",
    poi_zone_lower_atr_mult: "ATR multiplier for the lower side of the HTF POI zone.",
    use_space_to_target_filter: "Reject entries when there is not enough room to the opposite HTF swing for the minimum RR.",
    space_to_target_min_rr: "Minimum available R-multiple required before the opposite HTF swing blocks the trade.",
    use_choch_displacement_filter: "Require the LTF CHoCH break candle to have a strong body relative to ATR.",
    choch_displacement_atr_mult: "Minimum CHoCH candle body size in ATR multiples (for example 1.5 = body must be at least 1.5 ATR).",
    use_ltf_choch_trigger: "Enable/Disable LTF CHoCH Trigger for precise entries",
    ltf_choch_entry_window_bars: "Даем цене указанное количество свечей (напр. 6 баров = 1.5 часа на 15m) на подтверждение после касания уровня HTF.",
    require_choch_fvg: "Require the CHoCH displacement candle to leave a local Fair Value Gap.",
    use_rsi_filter: "Enable/Disable RSI checks for overbought/oversold conditions",
    rsi_period: "Lookback period for RSI indicator",
    rsi_overbought: "RSI level above which Longs are avoided (Too high)",
    rsi_oversold: "RSI level below which Shorts are avoided (Too low)",
    min_wick_to_range: "Minimum wick size relative to candle range (for Pin Bars). Wick must be ≥ this % of high-low.",

    max_body_to_range: "Maximum body size relative to total range (for Pin Bars). Body must be ≤ this % of high-low.",
    use_adx_filter: "Enable/Disable ADX (Trend Strength) Filter",
    adx_period: "Lookback period for ADX indicator",
    adx_threshold: "Minimum ADX value required to enter a trade (Trend Strength)",
    use_rsi_momentum: "Enable/Disable RSI Momentum (Long if > 50, Short if < 50)",
    rsi_momentum_threshold: "Threshold for RSI Momentum (usually 50)",

    pattern_hammer: "Hammer: bullish pin bar with long lower wick at bottom of trend",
    pattern_inverted_hammer: "Inverted Hammer: bullish pin bar with long upper wick at bottom of trend",
    pattern_shooting_star: "Shooting Star: bearish pin bar with long upper wick at top of trend",
    pattern_hanging_man: "Hanging Man: bearish pin bar with long lower wick at top of trend",
    pattern_bullish_engulfing: "Bullish Engulfing: two-candle bullish reversal pattern",
    pattern_bearish_engulfing: "Bearish Engulfing: two-candle bearish reversal pattern",

    run_mode_single: "Standard backtest over the full period with fixed parameters.",
    run_mode_optimize: "Grid search over Risk:Reward, SL Buffer (ATR), Trailing Stop Distance. Enter 3 values per param manually (no min/max). Results sorted by Sharpe. Pick best → Save as Template.",

    pivot_span: "Определяет, сколько свечей слева и справа нужно для подтверждения swing high/low на HTF. Влияет на чувствительность структуры: меньше значение = больше сигналов и больше шума, больше значение = структура медленнее, но чище. Средний рабочий ориентир: 2.",
    enable_structure_filter: "Разрешает входы только по направлению текущей HTF-структуры. Влияет на количество сделок и обычно снижает входы против тренда. Средний рабочий вариант: включено.",
    enable_fvg: "Включает поиск HTF Fair Value Gap как обязательного контекста для сетапа. Влияет на селективность: без него сигналов больше, но качество обычно ниже. Средний рабочий вариант: включено.",
    fvg_min_atr_mult: "Минимальный размер FVG в долях ATR на HTF. Влияет на качество зоны: выше значение отсекает слабые дисбалансы, но уменьшает число входов. Средний рабочий диапазон: 0.2-0.4, базово 0.2.",
    fvg_max_age_bars: "Максимальный возраст HTF FVG в барах, после которого зона считается устаревшей. Влияет на актуальность сетапов: меньше = свежее, но реже; больше = больше сигналов, но выше риск торговать старую зону. Средний ориентир: 30-50, базово 40.",
    use_midpoint: "Для limit-входа позволяет брать точку входа по середине FVG вместо уровня CHoCH. Влияет на цену входа: может улучшить RR, но часть сделок не будет исполнена. Средний вариант: выключено для более стабильного исполнения.",
    enable_sweep: "Требует sweep локальной ликвидности перед сетапом. Влияет на качество разворотного триггера и уменьшает случайные входы. Средний рабочий вариант: включено.",
    sweep_min_atr_mult: "Минимальная глубина sweep в ATR. Влияет на силу захвата ликвидности: выше = меньше, но чище входов. Средний рабочий диапазон: 0.15-0.3, базово 0.15.",
    enable_choch: "Включает подтверждение CHoCH после sweep. Влияет на подтвержденность входа: без него стратегия станет заметно агрессивнее. Средний рабочий вариант: включено.",
    choch_mode: "Режим подтверждения CHoCH. fast быстрее дает вход, confirmed ждет более завершенную структуру. Влияет на баланс между ранним входом и надежностью. Средний рабочий вариант: fast.",
    choch_entry_window_bars: "Сколько LTF-баров после подтверждения CHoCH дается на вход. Влияет на свежесть сетапа: меньше = строже и свежее, больше = больше шансов войти позже. Средний ориентир: 4-8, базово 6.",
    choch_max_pullaway_mult: "Максимально допустимое удаление цены от уровня CHoCH в ATR перед входом. Убирает запоздалые входы после сильного импульса. Средний рабочий диапазон: 1.0-1.5, базово 1.5.",
    displacement_required: "Требует, чтобы пробой CHoCH сопровождался импульсной свечой. Влияет на качество подтверждения и обычно уменьшает слабые пробои. Средний рабочий вариант: включено.",
    enable_displacement: "Включает отдельную проверку displacement-свечи. Влияет на строгость подтверждения импульса. Средний рабочий вариант: включено.",
    displacement_atr_mult: "Минимальный размер тела displacement-свечи в ATR. Влияет на силу подтверждения: выше = меньше, но сильнее сигналы. Средний рабочий диапазон: 0.8-1.2, базово 1.0.",
    displacement_close_threshold: "Насколько близко закрытие displacement-свечи должно быть к своему экстремуму. Влияет на качество импульса: выше = строже. Средний рабочий диапазон: 0.65-0.8, базово 0.7.",
    entry_type: "Тип входа: market входит сразу, limit ждет более выгодную цену. Влияет на исполнение и частоту пропущенных сделок. Средний практичный вариант: market, если важнее стабильное исполнение.",
    limit_mode: "Если выбран limit-вход, определяет точку лимит-ордера: уровень CHoCH или midpoint FVG. Влияет на цену входа и шанс исполнения. Средний вариант: choch_level.",
    sl_buffer_mult: "Отступ стопа от sweep extreme в ATR. Влияет на частоту выбивания и размер риска: выше = стоп дальше и сделок меньше, но шум выбивает реже. Средний рабочий диапазон: 0.15-0.3, базово 0.2.",
    tp_mode: "Логика тейк-профита: до ближайшей HTF-ликвидности или по фиксированному RR. Влияет на реалистичность целей и средний RR. Средний вариант: liquidity в структуре, rr для более стабильной оптимизации.",
    partial_tp: "Переключатель частичной фиксации прибыли. В текущей логике сильного эффекта может не давать, если частичное исполнение не задействовано в полном пайплайне. Средний безопасный вариант: выключено.",
    atr_period: "Период ATR для расчета волатильности, displacement и стоп-буфера. Влияет на чувствительность ко входам и стопам. Средний рабочий ориентир: 14.",
    min_rr_filter: "Минимальный доступный RR до входа. Отсекает сделки, где потенциальная цель слишком близко относительно стопа. Средний рабочий диапазон: 1.2-1.8, базово 1.5.",

    use_ote_filter: "OTE-фильтр: разрешает long только после достаточно глубокой коррекции в discount-зону, а short только в premium-зону. Влияет на глубину отката и обычно убирает входы слишком близко к экстремуму диапазона. Средний рабочий вариант: выключено, если уже включен min pullback; включать, когда нужна более строгая структурная фильтрация.",
    ote_min_retracement: "Нижняя граница OTE по retracement. Чем выше значение, тем глубже откат требуется перед входом. Влияет на селективность и количество сделок. Средний рабочий диапазон: 0.62-0.705, базово 0.62.",
    ote_max_retracement: "Верхняя граница OTE-зоны. Влияет в основном на диапазон аналитики и визуализации зоны, а не на основной допуск к входу. Средний рабочий ориентир: 0.79.",
    use_min_pullback_filter: "Фильтр минимальной коррекции от HTF-экстремума. Для long требует, чтобы цена отошла вниз от HTF high минимум на заданное число HTF ATR, и наоборот для short. Напрямую убирает входы 'на хаях' и 'на лоях'. Средний рабочий вариант: включено.",
    min_pullback_atr_mult: "Минимальная глубина коррекции от HTF high/low в ATR. Влияет на то, насколько далеко цена должна отойти от экстремума перед входом. Ниже 1.0 = больше сделок, но больше входов близко к экстремуму; выше 1.0 = строже и реже. Средний рабочий диапазон: 0.8-1.2, базово 1.0.",
};
