export const TOOLTIP_HINTS: Record<string, string> = {
    initial_capital: "Starting account balance in USD",
    risk_per_trade: "Percentage of capital risked per single trade (e.g. 1.0 = 1%)",
    max_drawdown: "Maximum allowed decline in account equity before stopping",
    leverage: "Multiplier for position size (technical use only, risk is controlled by % per trade)",

    symbol: "Trading pair to backtest (e.g. BTC/USDT)",
    start_date: "Backtest start date",
    end_date: "Backtest end date",
    timeframe_primary: "Higher timeframe for trend direction / EMA filter (e.g. 4h, 1d)",
    timeframe_secondary: "Lower timeframe for pattern detection and trade entries (e.g. 15m, 1h)",
    trailing_stop_distance: "Distance to trail the stop loss behind price (e.g. 0.02 = 2%)",
    breakeven_trigger_r: "Profit multiplier to trigger move to breakeven (e.g. 1.0 = Move stop to entry when profit hits 1R)",
    dynamic_position_sizing: "Adjust position size based on current capital/risk",
    position_cap_adverse: "Worst-case gap assumption for position cap (0.5=50%). Min 0.5 ensures max_drawdown is never exceeded. Higher = more conservative.",

    primary_timeframe: "The main timeframe for candle analysis (e.g. 4h, 1h)",
    min_range_factor: "Minimum candle range (high-low) relative to ATR. Candle range must be ≥ ATR × this factor. Filters flat markets.",
    use_pinbar_quality_filter: "Add stricter geometry checks for pin bars after TA-Lib detects a candidate.",
    pinbar_min_wick_to_body_ratio: "Minimum dominant wick/body ratio for a pin bar quality pass.",
    pinbar_max_opposite_wick_to_range: "Maximum allowed opposite wick as a share of total candle range for pin bars.",
    pinbar_close_near_extreme_threshold: "How close the close must be to the rejection extreme. 0.65 means the close must finish in the top/bottom 35% of the bar.",
    use_engulfing_quality_filter: "Add stricter body and close-location checks for engulfing candles after TA-Lib detects a candidate.",
    engulfing_min_body_to_range: "Minimum body size as a share of the current candle range for engulfing quality.",
    engulfing_min_body_to_atr: "Minimum body size in ATR multiples for engulfing quality.",
    engulfing_min_body_engulf_ratio: "Current engulfing body must be at least this multiple of the previous candle body.",
    engulfing_max_opposite_wick_to_range: "Maximum allowed wick against the direction of the engulfing candle.",
    engulfing_require_close_through_prev_extreme: "Require the engulfing candle to close beyond the previous candle high/low for extra confirmation.",
    use_trend_filter: "Enable/Disable trading only in direction of EMA trend",
    trend_ema_period: "Period for Exponential Moving Average to determine trend direction",
    risk_reward_ratio: "Target Profit/Risk ratio for trade exits",
    sl_buffer_atr: "Buffer added to Stop Loss based on ATR (volatility)",
    poi_zone_upper_atr_mult: "ATR multiplier for the upper side of the HTF POI zone.",
    poi_zone_lower_atr_mult: "ATR multiplier for the lower side of the HTF POI zone.",
    use_premium_discount_filter: "Allow longs only below the HTF equilibrium and shorts only above it.",
    use_space_to_target_filter: "Reject entries when there is not enough room to the opposite HTF swing for the minimum RR.",
    space_to_target_min_rr: "Minimum available R-multiple required before the opposite HTF swing blocks the trade.",
    use_choch_displacement_filter: "Require the LTF CHoCH break candle to have a strong body relative to ATR.",
    choch_displacement_atr_mult: "Minimum CHoCH candle body size in ATR multiples (for example 1.5 = body must be at least 1.5 ATR).",
    require_choch_fvg: "Require the CHoCH displacement candle to leave a local Fair Value Gap.",
    use_rsi_filter: "Enable/Disable RSI checks for overbought/oversold conditions",
    rsi_period: "Lookback period for RSI indicator",
    rsi_overbought: "RSI level above which Longs are avoided (Too high)",
    rsi_oversold: "RSI level below which Shorts are avoided (Too low)",
    min_wick_to_range: "Minimum wick size relative to candle range (for Pin Bars). Wick must be ≥ this % of high-low.",

    max_body_to_range: "Maximum body size relative to total range (for Pin Bars). Body must be ≤ this % of high-low.",
    use_adx_filter: "Enable/Disable ADX (Trend Strength) Filter",
    adx_period: "Lookback period for ADX indicator",
    adx_threshold: "Minimum ADX value required to enter a trade (Trend Strength)",
    use_rsi_momentum: "Enable/Disable RSI Momentum (Long if > 50, Short if < 50)",
    rsi_momentum_threshold: "Threshold for RSI Momentum (usually 50)",

    pattern_hammer: "Hammer: bullish pin bar with long lower wick at bottom of trend",
    pattern_inverted_hammer: "Inverted Hammer: bullish pin bar with long upper wick at bottom of trend",
    pattern_shooting_star: "Shooting Star: bearish pin bar with long upper wick at top of trend",
    pattern_hanging_man: "Hanging Man: bearish pin bar with long lower wick at top of trend",
    pattern_bullish_engulfing: "Bullish Engulfing: two-candle bullish reversal pattern",
    pattern_bearish_engulfing: "Bearish Engulfing: two-candle bearish reversal pattern",
};
